### ISSUE TITLE
PHP notice on WXR import - Undefined index: full 

### ISSUE THREAD

**Issue by tcrsavage** [humanmade/smart-media#5] opened 2018-11-13 17:37 UTC
Looks like this is probably related to the php notice below, seems to trigger for each image

<img width="1382" alt="screen shot 2018-11-13 at 17 35 55" src="https://user-images.githubusercontent.com/907521/48431860-af654780-e76a-11e8-88b4-92bfc7487ff3.png">

**Comment by tcrsavage** [comment] 2018-11-13 18:38
Correction here: The issue does not break WXR imports. Updating title

**Comment by fklein-lu** [comment] 2018-12-07 09:14
The issue also shows up randomly on other pages, and also Ajax requests.

**Comment by roborourke** [comment] 2019-04-30 16:49
Looks like this particular warning is fixed in 0.1.11. There are however two other similar warnings, 'width' and 'height' are not set on the attachment metadata which shouldn't really be possible.

I'm not sure what the root cause of that is. It can be patched with a just in time `getimagesize()` call if those values aren't set but there's a performance problem right there. Will need to dig in a bit to find the exact images with issues and check their meta data.

**Comment by rmccue** [comment] 2019-05-03 16:51
It seems like this is because `full` is a special-case for sizes internally. In my case, I'm using a starter theme which doesn't declare theme support for anything, and I think that's where this is coming from.

**Comment by roborourke** [comment] 2019-05-10 08:30
Found the issue - PR is up at #13

**Closed** 2019-05-10 14:26 UTC
Labels: bug
