### ISSUE TITLE
PHP error when viewing local media library containing files from the global content repository

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/smart-media#157] opened 2021-06-10 17:02 UTC
**Description**
When images are copied to the local site from the global content repository, a console error is reported by Query Monitor from Smart Media when viewing the media library for each image copied in this way.

![Screen Shot 2021-06-10 at 11 17 58 AM](https://user-images.githubusercontent.com/991511/121569093-a9e14400-c9dd-11eb-8060-759db69ee761.png)

```js
{ 
  key: "b6cd7fd43fa5260f17336f17c6ae907f", 
  type: "warning", 
  message: "Image metadata generation failed for image ID \"374\", this may require manual resolution.", 
  file: "vendor/humanmade/smart-media/inc/cropper/namespace.php", 
  line: 318, 
  stack: [
    0: "HM\\M\\C\\attachment_js()"
​    1: "apply_filters('wp_prepare_attachment_for_js')"
​​    2: "wp_prepare_attachment_for_js()"
​​    3: "array_map()"
​​    4: "wp_ajax_query_attachments()"
​​    5: "AssetManagerFramework\\LocalProvider->request()"
​​    6: "AssetManagerFramework\\Provider->request_items()"
​​    7: "AssetManagerFramework\\ajax_query_attachments()"
​​    8: "do_action('wp_ajax_query-attachments')"
  ]
  component: "Dependency: humanmade/smart-media" 
}
```

**Steps to reproduce**

1. Clear local site media library of all images/attachments that have been copied from the global content repository to start with a clean slate
2. Create a new post.
3. Create an image block and select an image from the global content repository.
4. Create a new image block. When the local media library loads, a single console error will appear.
5. Select and insert a new image from the global content repository.
6. Repeat steps 4 & 5. Now you will see two console errors, one for each image copied from the global repository.
7. Select an insert a new image from the global content repository.
8. Navigate to the Media Library. 3 console errors will appear like the below, one for each image that was copied from the global content repository.

**Screenshots**

_Local media library after inserting **one** image from the global content repository_
![Screen Shot 2021-06-10 at 11 08 27 AM](https://user-images.githubusercontent.com/991511/121568271-c2049380-c9dc-11eb-91b4-c0a6acdc3b83.png)

_Local media library after inserting **two** images from the global content repository_
![Screen Shot 2021-06-10 at 11 09 38 AM](https://user-images.githubusercontent.com/991511/121568659-27f11b00-c9dd-11eb-8fff-df95b741cfe1.png)

_Local media library page after copying **three** images from the global content repository_
![Screen Shot 2021-06-10 at 11 12 10 AM](https://user-images.githubusercontent.com/991511/121568682-2e7f9280-c9dd-11eb-9713-4fc38d58d939.png)

Detected on resolution of #32

**Comment by roborourke** [comment] 2021-06-11 11:04
Caused by missing / incorrect height meta data and fixed by https://github.com/humanmade/amf-wordpress/pull/15

This will result in Smart Media adding a load of data that enables the edit mode which we'll need to circumvent for now.

**Comment by roborourke** [comment] 2021-06-11 11:06
Note it will only be fixed for localised external files moving forward.

**Closed** 2021-06-11 11:07 UTC
Labels: bug
