### ISSUE TITLE
Featured Image no longer being set

### ISSUE THREAD

**Issue by stuartshields** [humanmade/smart-media#60] opened 2020-05-15 04:12 UTC
Since 0.2.9 it appears that the featured image cannot be set because of smart media.

## Steps to reproduce
1. Make sure 0.2.9 or above is installed (confirmed this bug happens on all versions since 0.2.9)
2. Try and add a Featured Image to a post
3. No featured image is added

## Versions affected
0.2.9 and above

As soon as I remove `&& ! frame.state( 'featured-image' )` from https://github.com/humanmade/smart-media/commit/1b804cea6b541c3a24975c755ee94714bd091ec7#diff-56f30d7639242a5cd3c9fc4ec673c541R98 a featured image can be added. 

If anyone else is needed, let me know. Since this was happening on a client project, I can't publicly upload a demo of the issue but will link one on Slack.

**Comment by roborourke** [comment] 2020-05-20 09:49
Hey @stuartshields I can't reproduce this on the twentynineteen and twentytwenty theme. I'm going to spin up your project to see if I can reproduce it with that and figure out if there's some custom code it's clashing with.

**Comment by roborourke** [comment] 2020-05-20 11:30
Fixed in 0.2.13

**Closed** 2020-05-20 11:30 UTC
Labels: bug

**Comment by stuartshields** [comment] 2020-05-21 00:18
@roborourke Thanks for fixing this! I really did think I was going insane as @abhishek-kaushik didn't have the same issue as me.
