### ISSUE TITLE
Media Library displaying different images on load

### ISSUE THREAD

**Issue by lachlanj** [humanmade/smart-media#83] opened 2020-08-25 08:37 UTC
### Describe the bug

When loading the Media Library on a post, the Media Library displays different media on re-open.

### To Reproduce
Steps to reproduce the behaviour:
1. Create a new post
2. Insert an image block
3. Get Media from Media Library
4. Look at what is being displayed Scroll down to load next lot of images
5. Close Modal
6. Re-open Modal (should show different media)

### Expected behaviour

Media displayed should all be the same. 

### Screenshots

![Kapture 2020-06-18 at 12 30 52](https://user-images.githubusercontent.com/15369210/84971241-a535d700-b15f-11ea-9040-755ed8faab2a.gif)

**Comment by roborourke** [comment] 2020-08-25 17:02
This isn't an easy fix and a little difficult to reproduce in the same dramatic way as the above example. It's to do with how the media modal loads data in. I'm not sure why it reloads all the attachments each time, but appears to keep whatever the last screen of attachments was available. It seems to be getting some state or pagination info from somewhere.

I'd like to make sure we can reproduce this on a clean Altis install to rule any project code behaviour.

**Comment by roborourke** [comment] 2020-08-26 09:58
I'm hoping improving the loading experience to prevent layout jitter will solve this to some extent https://github.com/humanmade/smart-media/pull/86

**Comment by roborourke** [comment] 2020-08-26 10:50
@lachlanj let me know if updating to the latest release 0.2.19 helps with this issue.

**Comment by lachlanj** [comment] 2020-08-27 01:53
@roborourke thanks for this! I'll try to get some time to test this in the next few days (currently off project)

**Comment by stuartshields** [comment] 2020-08-28 05:36
@roborourke and @lachlanj I've tested out the new fixes from 0.2.20 and it appears that this issue is also fixed.

**Comment by roborourke** [comment] 2020-08-28 09:41
Yerrrrssss! Thought it might. Alright closing this one out. Thanks for the bug report :)

**Closed by roborourke** 2020-08-28 09:41 UTC
